# Generated by Django 2.2 on 2020-05-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeed',
            new_name='ProfileFeedItem',
        ),
    ]
